name: "Main"

on:
  push:
    branches:
      - main
    tags: 
      - v*
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:    
      - main
    paths-ignore:
      - '**.md'

jobs:

  build-job:
    name: "Build native libraries ${{ matrix.platform.rid }}"
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Windows (x64), os: windows-latest, rid: win-x64 }
        - { name: Linux (x64), os: ubuntu-latest, rid: linux-x64 }
        - { name: macOS (x64+arm64), os: macos-latest, rid: osx }
    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@master
      with:
        submodules: 'recursive'

    - name: "Build native libraries (Windows)"
      if: ${{ startsWith(matrix.platform.rid, 'win') }}
      shell: bash
      run: ./library.sh

    - name: "Build native libraries (Unix)"
      if: ${{ !(startsWith(matrix.platform.rid, 'win')) }}
      shell: bash
      run: ./library.sh

    - name: "Upload native libraries"
      uses: actions/upload-artifact@v2
      with:
        name: "native-libraries-${{ matrix.platform.rid }}"
        path: './lib/${{ matrix.platform.rid }}'
